sendgrid/sendgrid-java

- src/main/java/com/sendgrid/SendGrid.java
Fix for To, ToName getting Jumbled.
Also found another bug in handling SendGrid Response. The error message sometimes appears in response Json as a "error" or "errors" key even thought the response has HTTP 200 ok status.. Added code change to handle this situation.
> Bug Fix #61 - To, ToName and Substitution values getting jumbled.

- pom.xml
- src/main/java/com/sendgrid/SendGrid.java
- src/test/java/com/sendgrid/SendGridTest.java
Issues: https://github.com/sendgrid/sendgrid-java/issues/138 & https://github.com/sendgrid/java-http-client/issues/8
Will allow to pass in a custom `Client` (that itself might have a custom `CloseableHttpClient` to use proxies for example).
**I can provide a signed CLA once I know this PR makes sense as it is** :wink:
> [Enhancement] allow using custom Client

- src/main/java/com/sendgrid/helpers/mail/objects/Attachments.java
- src/test/java/com/sendgrid/helpers/AttachmentBuilderTest.java
Fixes #134.
Adds an attachment builder class that helps creating content from InputStream as well as simple strings.
> Adds an attachment builder that supports InputStream content.

- src/main/java/com/sendgrid/helpers/mail/objects/Personalization.java
When calling a getXyz() method on a Mail object, where xyz is some object implementing Collection, if xyz is null then an empty collection will be returned (currently returns null).
> Return empty collections in place of nulls

- src/main/java/com/sendgrid/SendGrid.java
- src/main/java/com/sendgrid/helpers/mail/Mail.java
- src/main/java/com/sendgrid/helpers/mail/objects/ASM.java
- src/main/java/com/sendgrid/helpers/mail/objects/Attachments.java
- src/main/java/com/sendgrid/helpers/mail/objects/BccSettings.java
- src/main/java/com/sendgrid/helpers/mail/objects/ClickTrackingSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/Content.java
- src/main/java/com/sendgrid/helpers/mail/objects/Email.java
- src/main/java/com/sendgrid/helpers/mail/objects/FooterSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/GoogleAnalyticsSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/MailSettings.java
- src/main/java/com/sendgrid/helpers/mail/objects/OpenTrackingSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/Personalization.java
- src/main/java/com/sendgrid/helpers/mail/objects/Setting.java
- src/main/java/com/sendgrid/helpers/mail/objects/SpamCheckSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/SubscriptionTrackingSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/TrackingSettings.java
This addresses issue https://github.com/sendgrid/sendgrid-java/issues/130
> Added Javadocs.

- README.md
I think the logo and badges should not be on the same line
> update readme - logo on separate line

- USAGE.md
Change the sentence 'The the parent may then associate the whitelabel via the subuser management tools.' to 'The parent may then associate the whitelabel via the subuser management tools.'.
> Remove redundant word 'the' from USAGE.md.

- .github/PULL_REQUEST_TEMPLATE
Created a PULL_REQUEST_TEMPLATE for description of changes based on the link to the template given in #314
> Create a PULL_REQUEST_TEMPLATE

- docker/Dockerfile
- docker/README.md
- docker/USAGE.md
- docker/entrypoint.sh
Added support for Java 8. Note that due to Oracle's licensing, this only supports Java 8.
This fixes issue https://github.com/sendgrid/sendgrid-java/issues/230
> Adding Docker support.

- .travis.yml
Closes: #367 #363 
**Description of the change**:
I fixed the prism issue, it needed sudo to work. Also updated jdk to 8(openjdk8 and oraclejdk8)
Fixes #367 and #363 .
removed sudo:false, so that sudo will be enabled(that is the default). Without sudo, prism was giving permission denied error. Also, changed matrix to use jdk8(both openjdk and oraclejdk). You could just remove matrix, but in my experience, it's easier to ensure that only those builds are created that we want, when we use matrix. Otherwise, sometimes two different options can create unnecessary/unexpected builds. So I kept matrix.
> Fixed prism issue and changed jdk to 8

- src/test/java/com/sendgrid/TestRequiredFilesExist.java
Closes: #355 
**Description of the change**:
Added unittest to check for specific repo files mentioned in https://github.com/sendgrid/sendgrid-java/issues/355
If you have questions, please send an email [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
> Added unittest to check for specific repo files

- LICENSE.md
- src/test/java/com/sendgrid/LicenseTest.java
Closes: #354 
**Description of the change**:
If you have questions, please send an email [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
> Test to check year in license file

- build.gradle
- pom.xml
Fixes #227, #192 
hi @thinkingserious , as a follow up on this https://github.com/sendgrid/sendgrid-java/pull/227.
> Updates jackson dependencies to the latest version.

- README.md
Replace compile with implementation
We appreciate the effort for this pull request but before that please make sure you read the contribution guidelines given above, then fill out the blanks below.
- Replaces compile with implementation on the README.md
> Update README to use implementation instead of compile

- examples/accesssettings/README.md
Cleanup of README for examples/accesssettings
Fixes #474 
🎃
> Fix formatting of README in examples/accesssettings 🎃

- src/main/java/com/sendgrid/SendGrid.java
- src/test/java/com/sendgrid/SendGridTest.java
SendGrid API has a feature that allows a parent account to impersonate
subusers by including an HTTP header "on-behalf-of" in the API request.
This commit enables users to use impersonation.
Fixes #404 
- This PR allows users to impersonate subusers
If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.
> Fix #404 Add ability to impersonate subusers

- bin/com/sendgrid/helpers/README.md
- build.gradle
- pom.xml
- src/main/java/com/sendgrid/helpers/README.md
Greetings,
The Jackson dependencies used by this project are version `2.9.5`, which are prone to multiple CVE-registered vulnerabilities (https://www.cvedetails.com/vulnerability-list/vendor_id-15866/Fasterxml.html).
Upgrading to `2.9.9` should solve those issues, although I'm afraid I'm in no position to ascertain that.
> Update Jackson dependencies to the latest version

- .github/PULL_REQUEST_TEMPLATE
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Just a few whitespace error fixes in the markdown files, as well as two typo fixes:
- `Github` -> `GitHub`
- `Sendgrid` -> `SendGrid`
> docs: Fix whitespace errors and typos

- pom.xml
Fixes https://github.com/sendgrid/sendgrid-java/issues/634
Using a version range like this results in maven attempting to get SNAPSHOT information for the dependency since it's possible a SNAPSHOT release would match the version range. It's not a big deal, but there are better approaches. The idea was we want to pick up the latest 4.X version of java-http-client, but even a version range does not guarantee this. It only guarantees that a 4.X version will be used (not necessarily the latest release). What we really want is the latest non-snapshot, minor version release for all dependencies, not just java-http-client. Also note that Maven version ranges perform basic string comparison so even it they were capable of getting the latest release for a dependency, it might not actually be the …
> fix: don't use dependency version ranges

- USE_CASES.md
- examples/helpers/mail/MultipleEmailsMultipleRecipients.java
- examples/helpers/mail/SingleEmailMultipleRecipients.java
We have similar examples in other languages and they provide a clear distinction between the two use cases.
Fixes #629
> docs: add multi-recipient examples

- pom.xml
By upgrading the `maven-shade-plugin` the `bcprov-jdk15on` artifact (which contains JDK 9+ classes) can also be used when building the project using JDK 8. This change reverts d9f4413707c38cd7c702d04574b207da56343002.
Resolves #636.
> fix: Replace `bcprov-jdk15to18` with `bcprov-jdk15on`

- src/main/java/com/sendgrid/APICallback.java
- src/main/java/com/sendgrid/RateLimitException.java
- src/main/java/com/sendgrid/SendGrid.java
- src/main/java/com/sendgrid/SendGridAPI.java
- src/main/java/com/sendgrid/helpers/mail/Mail.java
- src/main/java/com/sendgrid/helpers/mail/objects/ASM.java
- src/main/java/com/sendgrid/helpers/mail/objects/Attachments.java
- src/main/java/com/sendgrid/helpers/mail/objects/BccSettings.java
- src/main/java/com/sendgrid/helpers/mail/objects/ClickTrackingSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/Content.java
- src/main/java/com/sendgrid/helpers/mail/objects/Email.java
- src/main/java/com/sendgrid/helpers/mail/objects/FooterSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/GoogleAnalyticsSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/MailSettings.java
- src/main/java/com/sendgrid/helpers/mail/objects/OpenTrackingSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/Personalization.java
- src/main/java/com/sendgrid/helpers/mail/objects/Setting.java
- src/main/java/com/sendgrid/helpers/mail/objects/SpamCheckSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/SubscriptionTrackingSetting.java
- src/main/java/com/sendgrid/helpers/mail/objects/TrackingSettings.java
- src/test/java/com/sendgrid/LicenseTest.java
- src/test/java/com/sendgrid/SendGridTest.java
- src/test/java/com/sendgrid/TestRequiredFilesExist.java
- (Mostly) automatically reformatted code using IntelliJ IDEA to match the Google Style Guide (as documented in CONTRIBUTING.md).
- 2 space indent, where it wasn't already.
- Line wrap at 100 characters, where it wasn't already.
- Wildcard imports were replaced with explicit imports.
- Unused imports were removed.
- Annotations were put onto their own line, and additional lines added for readability where necessary.
- Braces were added to if-statements that didn't already have them.
- Also made some minor edits, e.g. as suggested by IntelliJ IDEA (e.g. public --> private).
This will help with getting the code into shape before style conformance is required as per issue #472 and pull request #496.
See also:
- https://github.com/google/google-java-format
- …
> chore: tidied up a little

- CHANGELOG.md
- CONTRIBUTING.md
- TROUBLESHOOTING.md
- USAGE.md
- USE_CASES.md
I left "whitelabeling" and "subusers" as it was. I think is better not to change those words.
Fixes #476
> doc: Run *.md documents through Grammer.ly

- src/main/java/com/sendgrid/BaseInterface.java
- src/test/java/com/sendgrid/SendGridTest.java
Fixes #214 
This PR makes it so `headers` set on a `Request` object are utilized in final request sent to the SendGrid API. Currently, only the header values set on the `SendGrid` object itself are utilized.
I also swapped the `for each` out for `putAll` - certainly not married to that change if it is unwarranted.
> fix: Utilize headers set on the Request object

- .github/workflows/update-dependencies.yml
- Makefile
Jira: [DI-1972](https://issues.corp.twilio.com/browse/DI-1972)
> feat: add GH action to update dependencies

- .github/workflows/update-dependencies.yml
- pom.xml
Tested on [this run](https://github.com/sendgrid/sendgrid-java/runs/5697879895?check_suite_focus=true)
> fix: override default gh token

- pom.xml
- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
pom.xml
> jackson-databind before 2.13.0 allows a Java StackOverflow exception and denial of service via a large depth of nested objects.
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
> chore: security upgrade jackson-databind from 2.13.0 to 2.13.2

- src/main/java/com/sendgrid/BaseInterface.java
- src/test/java/com/sendgrid/SendGridTest.java
A short description of what this PR does.
> feat: Add data residency for eu and global regions

- pom.xml
This mitigates CVE-2023-33201.
ref. https://github.com/bcgit/bc-java/wiki/CVE-2023-33201
> chore: updates bouncy castle to 1.75 (latest 1.7x)

- src/main/java/com/sendgrid/constant/ApplicationConstants.java
- src/main/java/com/sendgrid/http/ApiResponse.java
- src/main/java/com/sendgrid/http/Request.java
> chore: fixed request and response

- src/main/java/com/sendgrid/ApiKeySendGrid.java
- src/main/java/com/sendgrid/constant/Domains.java
- src/main/java/com/sendgrid/constant/EnumConstants.java
- src/main/java/com/sendgrid/constant/ErrorMessages.java
- src/main/java/com/sendgrid/exception/ApiErrorResponse.java
- src/main/java/com/sendgrid/exception/GenericApiError.java
- src/main/java/com/sendgrid/exception/GenericError.java
- src/main/java/com/sendgrid/http/ApiKeyRestClient.java
- src/main/java/com/sendgrid/http/Request.java
- src/main/java/com/sendgrid/util/Utility.java
Data Residency feature completed and encoded query params.
> chore: Region set and encode query params

- .gitignore
- src/main/java/com/sendgrid/exception/RestException.java
- src/main/java/com/sendgrid/http/ApiKeyRestClient.java
- src/main/java/com/sendgrid/http/Request.java
- src/main/java/com/sendgrid/http/auth/TokenStrategy.java
> chore: Modify request

- .github/workflows/test-and-deploy.yml
- pom.xml
Moving the Bouncy Castle dependency to the test scope
> chore: move Bouncy Castle dependency to test scope
