sendgrid/sendgrid-java

src/main/java/com/sendgrid/SendGrid.java

Caches email.smtpapi.jsonString() so we only have to call it once

---

README.md

Spelling ;)

---

README.md

Reverts sendgrid/sendgrid-java#88

Revert "Fixing a typo in the README"

---

CONTRIBUTING.md

While I was reading the **CONTRIBUTING** section to learn how to contribute, I stumbled upon this broken link. Hope this helps!

Contributing.md broken link updated

---

CONTRIBUTING.md
USAGE.md

Update USAGE.md and CONTRIBUTING.md

---

TROUBLESHOOTING.md

Add "viewing request body" section to troubleshooting

---

CHANGELOG.md
TROUBLESHOOTING.md
USAGE.md
proposals/mail-helper-refactor.md

**Update:** Failing build, but looks unrelated; all changes are in markdown files.

Spelling corrections in `.md` files

---

README.md

Update readme - added maven central badge

---

USAGE.md

Fix a typo

---

USAGE.md

replaced "visible by recipient" by "visible to recipient"

correction of typo in USAGE.md

---

.travis.yml

Prism isn't starting. So, we wait longer

Quick and dirty changes to wait for prism

---

.github/PULL_REQUEST_TEMPLATE

Closes: #[Issue number]
**Description of the change**: use same format for PR template with other repos
If you have questions, please send an email [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

update github PR template

---

.env_sample
.gitignore
README.md

Add .env_sample file

---

examples/whitelabel/ips.java

Closes: #[Issue number]
**Description of the change**:
If you have questions, please send an email [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

Fix "similar-code" issue in examples/whitelabel/ips.java

---

README.md

- 
- 
If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

Added coders tag

---

README.md

Link to a directly signable, online version of CLA instead of a copy of the CLA for convenience
- Links to a signable, online version of the CLA instead of a copy to the CLA which can't be signed directly

Link to the online version of CLA in README.md

---

README.md

docs: fix a minor type in README

---

CONTRIBUTING.md

... from the out-of-date http://checkstyle.sourceforge.net/reports/google-java-style.html (last updated 2014-03-21)
... to https://google.github.io/styleguide/javaguide.html (last updated 2018-05-22)
See also https://github.com/google/styleguide/blob/gh-pages/javaguide.html
- Not applicable; there is no development branch yet.
- Not applicable.
- Not applicable.
- Not applicable.

docs: Update the link for Google's Style Guide

---

src/main/java/com/sendgrid/helpers/mail/objects/Setting.java
src/test/java/com/sendgrid/helpers/mail/objects/SettingsSerializationTest.java

fix: correct the serialization of Setting to include non-null values

---

README.md

docs: fix link to jar file

---

README.md

Somewhere along the line, the number seems to have been replaced with a
version number.
Changes the README to include the number of free emails for the first 30 days instead of showing a version number there. The number has been confirmed from [https://sendgrid.com/resource/faq/](https://sendgrid.com/resource/faq/).
If you have questions, please file a [support ticket](https://support.sendgrid.com), or create a GitHub Issue in this repository.

docs: Fix number of free emails in README

---

pom.xml

Updates bouncycastle to the latest version, 1.7.6, follow up to #741

chore: updates bouncy castle to 1.76 (latest 1.7x)

---

LICENSE
pom.xml

Update jackson version and licence year

chore: update jackson version and licence year

---

src/main/java/com/sendgrid/constant/ApplicationConstants.java
src/main/java/com/sendgrid/constant/Config.java
src/main/java/com/sendgrid/http/ApiResponse.java
src/main/java/com/sendgrid/http/Request.java

chore: fix response body

---

src/main/java/com/sendgrid/exception/ApiErrorResponse.java
src/main/java/com/sendgrid/http/ApiKeyRestClient.java

fix error response and api key http client.

chore: Fix error response

---

src/main/java/com/sendgrid/http/Request.java
src/main/java/com/sendgrid/http/auth/TokenStrategy.java

Remove Builder pattern from request as it creates difficulty in inheritance.

chore: Modify request

---

CHANGELOG.md
README.md
UPGRADE.md

Added UPGRADE.md, added changelog for RC, added examples in README.md

chore: added upgrade guide and readme updates

---

src/main/java/com/sendgrid/BaseInterface.java
src/test/java/com/sendgrid/SendGridTest.java

chore: Update version
